### ISSUE TITLE
Typo in notes on ODEs

### ISSUE THREAD

**Issue by BogdanRajkov** [AustenLamacraft/part-ii-computational-physics#3]
There is a typo in [line 58](https://github.com/AustenLamacraft/part-ii-computational-physics/blob/5b27191a57a8311ed791c39e31989ed3dfa98e03/notes/ode.qmd#L58) of notes/ode.qmd; the reference to the section on floating points is ill-defined.

**Comment by AustenLamacraft** [comment]
Thanks. Should be removed now (unfortunately referencing between sections in different chapters doesn't work with the current format)

**Comment by AustenLamacraft** [comment]
Thanks. Should be removed now (unfortunately referencing between sections in different chapters doesn't work with the current format)
