### ISSUE TITLE
Unable to run using VScode with Quarto

### ISSUE THREAD

**Issue by Takodachi6969** [AustenLamacraft/part-ii-computational-physics#4]
While trying tirelessly to render these lecture notes, there were particular files with names that were too long to unzip, hence I cannot use localized VScode to render them. I also tried to download Git and clone it, quarto again failed me. 

Could we have rendered PDF notes? I tried it and it didn't work that well.

**Comment by AustenLamacraft** [comment]
If you want to just view the site you can just open `_site/index.html` and go from there. Or do you want to do something more? 

I think I tried rendering PDF and it doesn't look nice. Maybe something can be done, but if you have the site, you can use it offline...
